/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void ManualControl_Click(GButton source, GEvent event) { //_CODE_:ManualControl:905006:
  println("ManualControl - GButton >> GEvent." + event + " @ " + millis());
  
  myPort.clear();
  myPort.write("j");
  
  if (ManualControlWindow == null) {
    createManualControlWindow();
  } else {
    ManualControlWindow.setVisible(!ManualControlWindow.isVisible());
  }
  
} //_CODE_:ManualControl:905006:

public void SemiAuto_Click(GButton source, GEvent event) { //_CODE_:SemiAuto:580310:
  println("SemiAuto - GButton >> GEvent." + event + " @ " + millis());
  
  myPort.clear();
  myPort.write("k");
  
  if (SemiAutoControlWindow == null) {
    createSemiAutoControlWindow();
  } else {
    SemiAutoControlWindow.setVisible(!SemiAutoControlWindow.isVisible());
  }
  
} //_CODE_:SemiAuto:580310:

public void FullAuto_Click(GButton source, GEvent event) { //_CODE_:FullAuto:470484:
  println("FullAuto - GButton >> GEvent." + event + " @ " + millis());
  
  myPort.clear();
  myPort.write("l");

  if (FullAutoControlWindow == null) {
    createFullAutoControlWindow();
  } else {
    FullAutoControlWindow.setVisible(!FullAutoControlWindow.isVisible());
  }
  
} //_CODE_:FullAuto:470484:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  G4P.setDisplayFont("Arial", G4P.PLAIN, 20);
  G4P.setInputFont("Arial", G4P.PLAIN, 18);
  G4P.setSliderFont("Arial", G4P.PLAIN, 18);
  surface.setTitle("Zumo Control Application");
  Title = new GLabel(this, 200, 75, 200, 75);
  Title.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  Title.setText("Zumo Control Application");
  Title.setOpaque(false);
  ManualControl = new GButton(this, 50, 250, 125, 75);
  ManualControl.setText("Manual Control");
  ManualControl.addEventHandler(this, "ManualControl_Click");
  SemiAuto = new GButton(this, 237, 250, 125, 75);
  SemiAuto.setText("Semi Auto Control");
  SemiAuto.setLocalColorScheme(GCScheme.RED_SCHEME);
  SemiAuto.addEventHandler(this, "SemiAuto_Click");
  FullAuto = new GButton(this, 425, 250, 125, 75);
  FullAuto.setText("Full Auto Control");
  FullAuto.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  FullAuto.addEventHandler(this, "FullAuto_Click");
  Name = new GLabel(this, 10, 575, 325, 25);
  Name.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  Name.setText("Created by Reece Wareham");
  Name.setOpaque(false);
}

// Variable declarations 
// autogenerated do not edit
GLabel Title; 
GButton ManualControl; 
GButton SemiAuto; 
GButton FullAuto; 
GLabel Name; 
